name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-Buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: avinashyadavpuresoftware
          password: Avinash@8794
      - name: Build and Publish ddtrace_rb_1.9.3
        uses: docker/build-push-action@v2
        with:
         context: ./1.9.3
         file: ./1.9.3/Dockerfile
         platforms: linux/arm64
         push: true
         tags: avinashyadavpuresoftware/ddtrace_rb_1.9.3:latest_arm
      - name: Build and Publish ddtrace_rb_2.0.0
        uses: docker/build-push-action@v2
        with:
         context: ./2.0.0
         file: ./2.0.0/Dockerfile
         platforms: linux/arm64
         push: true
         tags: avinashyadavpuresoftware/ddtrace_rb_2.0.0:latest_arm
      - name: Build and Publish ddtrace_rb_2.1.10
        uses: docker/build-push-action@v2
        with:
         context: ./2.1.10
         file: ./2.1.10/Dockerfile
         platforms: linux/arm64
         push: true
         tags: avinashyadavpuresoftware/ddtrace_rb_2.1.10:latest_arm
         
         
      - name: Build and Publish ddtrace_rb_2.3.7
        uses: docker/build-push-action@v2
        with:
         context: ./2.3.7
         file: ./2.3.7/Dockerfile
         platforms: linux/arm64
         push: true
         tags: avinashyadavpuresoftware/ddtrace_rb_2.3.7:latest_arm
         
         
      - name: Build and Publish ddtrace_rb_2.4.4
        uses: docker/build-push-action@v2
        with:
         context: ./2.4.4
         file: ./2.4.4/Dockerfile
         platforms: linux/arm64
         push: true
         tags: avinashyadavpuresoftware/ddtrace_rb_2.4.4:latest_arm


